version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  proxy:
    image: haproxytech/haproxy-alpine:2.4
    networks:
      - my_network
    depends_on:
      - web1
      - web2
      - web3
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - "/home/lukas/OneDrive/Dokumente/Studium/4. Semester/Cloud Computing/HAProxyTest:/usr/local/etc/haproxy:ro"
